EMBEDDING_DIM = 50
VOCAB_SIZE = 10000
MAX_SENTENCE_LENGTH = 20

DROP_LSTM = 0.8
DROP_DENSE = 0.7

HIDDEN_SIZE = 100
NNUM_LAYERS = 2
ACTIVATION_FUNCTION = 'relu'
MAX_GRAD_NORM = 5
SHARED_EMB_AND_SOFTMAX = False
LEARNING_RATE = 0.1
BATCH_SIZE = 32
EPOCH = 2


CHECKPOINT_PATH = './model/model_ckpt'
RAW_DATA_PATH = './raw_chat_corpus/ptt-42w/Gossiping-QA-Dataset.txt'
RAW_DATA_SIMPLE = './data/RAW_DATA.txt'
VOCAB_PATH = './data/VOCAB.txt'